pub mod audio;
pub mod backend;
#[cfg(target_os = "macos")]
pub mod chat;
pub mod clone;
pub mod config;
pub mod db;
pub mod init;
pub mod input;
pub mod mcp;
pub mod pack;
#[cfg(target_os = "macos")]
pub mod stt;
